import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto_Mono, Lobster, Lato, Fira_Sans } from "next/font/google";

const roboto = Roboto_Mono({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
const lato = Lato({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
const as = Lobster({
  family: ["Lobster Two", "sans-serif"],
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});
const fira = Fira_Sans({
  family: ["Fira Sans", "sans-serif"],
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fira.className}>{children}</body>
    </html>
  );
}
